project_id = "tyler-james-os"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[db.pooler]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://tyler-james-os.vercel.app"]
jwt_expiry = 3600
enable_signup = true

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_OAUTH_CLIENT_ID)"
secret = "env(GOOGLE_OAUTH_CLIENT_SECRET)"
